# Generated by Django 6.0.4 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurso",
                    models.CharField(
                        choices=[
                            ("salon_a", "Salon A"),
                            ("salon_b", "Salon B"),
                            ("laboratorio", "Laboratorio"),
                            ("auditorio", "Auditorio"),
                            ("equipo_video", "Equipo de video"),
                        ],
                        max_length=30,
                        verbose_name="recurso",
                    ),
                ),
                ("responsable", models.CharField(max_length=120, verbose_name="responsable")),
                ("correo", models.EmailField(max_length=254, verbose_name="correo de contacto")),
                ("fecha", models.DateField(verbose_name="fecha")),
                ("hora_inicio", models.TimeField(verbose_name="hora de inicio")),
                ("hora_fin", models.TimeField(verbose_name="hora de fin")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripcion")),
                (
                    "estado",
                    models.CharField(
                        choices=[("activa", "Activa"), ("cancelada", "Cancelada")],
                        default="activa",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.TextField(blank=True, verbose_name="motivo de cancelacion"),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True, verbose_name="creada en")),
                ("actualizada_en", models.DateTimeField(auto_now=True, verbose_name="actualizada en")),
            ],
            options={
                "verbose_name": "reserva",
                "verbose_name_plural": "reservas",
                "ordering": ["fecha", "hora_inicio", "recurso"],
            },
        ),
    ]
